POST http://127.0.0.1:5050/secret/create
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}

###
POST http://127.0.0.1:5050/key/open
Content-Type: application/json

{
"key": "hDHrEfAXkF_CqUCWHDRVYPH71nekdBiny28ELjGGECc="
}